/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiveCodeRouteImport } from './routes/receive.$code'
import { Route as ApiPublicSharesCreateRouteImport } from './routes/api/public/shares.create'
import { Route as ApiPublicSharesCodeRouteImport } from './routes/api/public/shares.$code'
import { Route as ApiPublicDownloadCodeRouteImport } from './routes/api/public/download.$code'
import { Route as ApiPublicCronCleanupRouteImport } from './routes/api/public/cron.cleanup'
import { Route as ApiPublicConsumeCodeRouteImport } from './routes/api/public/consume.$code'
import { Route as ApiPublicSharesCodeHeartbeatRouteImport } from './routes/api/public/shares.$code.heartbeat'
import { Route as ApiPublicSharesCodeDeactivateRouteImport } from './routes/api/public/shares.$code.deactivate'

const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveCodeRoute = ReceiveCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ReceiveRoute,
} as any)
const ApiPublicSharesCreateRoute = ApiPublicSharesCreateRouteImport.update({
  id: '/api/public/shares/create',
  path: '/api/public/shares/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesCodeRoute = ApiPublicSharesCodeRouteImport.update({
  id: '/api/public/shares/$code',
  path: '/api/public/shares/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadCodeRoute = ApiPublicDownloadCodeRouteImport.update({
  id: '/api/public/download/$code',
  path: '/api/public/download/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCleanupRoute = ApiPublicCronCleanupRouteImport.update({
  id: '/api/public/cron/cleanup',
  path: '/api/public/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsumeCodeRoute = ApiPublicConsumeCodeRouteImport.update({
  id: '/api/public/consume/$code',
  path: '/api/public/consume/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesCodeHeartbeatRoute =
  ApiPublicSharesCodeHeartbeatRouteImport.update({
    id: '/heartbeat',
    path: '/heartbeat',
    getParentRoute: () => ApiPublicSharesCodeRoute,
  } as any)
const ApiPublicSharesCodeDeactivateRoute =
  ApiPublicSharesCodeDeactivateRouteImport.update({
    id: '/deactivate',
    path: '/deactivate',
    getParentRoute: () => ApiPublicSharesCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRouteWithChildren
  '/send': typeof SendRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRouteWithChildren
  '/send': typeof SendRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receive': typeof ReceiveRouteWithChildren
  '/send': typeof SendRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/receive'
    | '/send'
    | '/receive/$code'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/receive'
    | '/send'
    | '/receive/$code'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/receive'
    | '/send'
    | '/receive/$code'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiveRoute: typeof ReceiveRouteWithChildren
  SendRoute: typeof SendRoute
  ApiPublicConsumeCodeRoute: typeof ApiPublicConsumeCodeRoute
  ApiPublicCronCleanupRoute: typeof ApiPublicCronCleanupRoute
  ApiPublicDownloadCodeRoute: typeof ApiPublicDownloadCodeRoute
  ApiPublicSharesCodeRoute: typeof ApiPublicSharesCodeRouteWithChildren
  ApiPublicSharesCreateRoute: typeof ApiPublicSharesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive/$code': {
      id: '/receive/$code'
      path: '/$code'
      fullPath: '/receive/$code'
      preLoaderRoute: typeof ReceiveCodeRouteImport
      parentRoute: typeof ReceiveRoute
    }
    '/api/public/shares/create': {
      id: '/api/public/shares/create'
      path: '/api/public/shares/create'
      fullPath: '/api/public/shares/create'
      preLoaderRoute: typeof ApiPublicSharesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$code': {
      id: '/api/public/shares/$code'
      path: '/api/public/shares/$code'
      fullPath: '/api/public/shares/$code'
      preLoaderRoute: typeof ApiPublicSharesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$code': {
      id: '/api/public/download/$code'
      path: '/api/public/download/$code'
      fullPath: '/api/public/download/$code'
      preLoaderRoute: typeof ApiPublicDownloadCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cleanup': {
      id: '/api/public/cron/cleanup'
      path: '/api/public/cron/cleanup'
      fullPath: '/api/public/cron/cleanup'
      preLoaderRoute: typeof ApiPublicCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consume/$code': {
      id: '/api/public/consume/$code'
      path: '/api/public/consume/$code'
      fullPath: '/api/public/consume/$code'
      preLoaderRoute: typeof ApiPublicConsumeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$code/heartbeat': {
      id: '/api/public/shares/$code/heartbeat'
      path: '/heartbeat'
      fullPath: '/api/public/shares/$code/heartbeat'
      preLoaderRoute: typeof ApiPublicSharesCodeHeartbeatRouteImport
      parentRoute: typeof ApiPublicSharesCodeRoute
    }
    '/api/public/shares/$code/deactivate': {
      id: '/api/public/shares/$code/deactivate'
      path: '/deactivate'
      fullPath: '/api/public/shares/$code/deactivate'
      preLoaderRoute: typeof ApiPublicSharesCodeDeactivateRouteImport
      parentRoute: typeof ApiPublicSharesCodeRoute
    }
  }
}

interface ReceiveRouteChildren {
  ReceiveCodeRoute: typeof ReceiveCodeRoute
}

const ReceiveRouteChildren: ReceiveRouteChildren = {
  ReceiveCodeRoute: ReceiveCodeRoute,
}

const ReceiveRouteWithChildren =
  ReceiveRoute._addFileChildren(ReceiveRouteChildren)

interface ApiPublicSharesCodeRouteChildren {
  ApiPublicSharesCodeDeactivateRoute: typeof ApiPublicSharesCodeDeactivateRoute
  ApiPublicSharesCodeHeartbeatRoute: typeof ApiPublicSharesCodeHeartbeatRoute
}

const ApiPublicSharesCodeRouteChildren: ApiPublicSharesCodeRouteChildren = {
  ApiPublicSharesCodeDeactivateRoute: ApiPublicSharesCodeDeactivateRoute,
  ApiPublicSharesCodeHeartbeatRoute: ApiPublicSharesCodeHeartbeatRoute,
}

const ApiPublicSharesCodeRouteWithChildren =
  ApiPublicSharesCodeRoute._addFileChildren(ApiPublicSharesCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiveRoute: ReceiveRouteWithChildren,
  SendRoute: SendRoute,
  ApiPublicConsumeCodeRoute: ApiPublicConsumeCodeRoute,
  ApiPublicCronCleanupRoute: ApiPublicCronCleanupRoute,
  ApiPublicDownloadCodeRoute: ApiPublicDownloadCodeRoute,
  ApiPublicSharesCodeRoute: ApiPublicSharesCodeRouteWithChildren,
  ApiPublicSharesCreateRoute: ApiPublicSharesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
