/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiveCodeRouteImport } from './routes/receive_.$code'
import { Route as ApiPublicSharesCreateRouteImport } from './routes/api/public/shares.create'
import { Route as ApiPublicSharesCodeRouteImport } from './routes/api/public/shares.$code'
import { Route as ApiPublicDownloadCodeRouteImport } from './routes/api/public/download.$code'
import { Route as ApiPublicCronCleanupRouteImport } from './routes/api/public/cron.cleanup'
import { Route as ApiPublicConsumeCodeRouteImport } from './routes/api/public/consume.$code'
import { Route as ApiPublicAdminSharesRouteImport } from './routes/api/public/admin.shares'
import { Route as ApiPublicAdminLoginRouteImport } from './routes/api/public/admin.login'
import { Route as ApiPublicAdminConfigRouteImport } from './routes/api/public/admin.config'
import { Route as ApiPublicSharesCodeHeartbeatRouteImport } from './routes/api/public/shares.$code.heartbeat'
import { Route as ApiPublicSharesCodeDeactivateRouteImport } from './routes/api/public/shares.$code.deactivate'

const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveCodeRoute = ReceiveCodeRouteImport.update({
  id: '/receive_/$code',
  path: '/receive/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesCreateRoute = ApiPublicSharesCreateRouteImport.update({
  id: '/api/public/shares/create',
  path: '/api/public/shares/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesCodeRoute = ApiPublicSharesCodeRouteImport.update({
  id: '/api/public/shares/$code',
  path: '/api/public/shares/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadCodeRoute = ApiPublicDownloadCodeRouteImport.update({
  id: '/api/public/download/$code',
  path: '/api/public/download/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCleanupRoute = ApiPublicCronCleanupRouteImport.update({
  id: '/api/public/cron/cleanup',
  path: '/api/public/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsumeCodeRoute = ApiPublicConsumeCodeRouteImport.update({
  id: '/api/public/consume/$code',
  path: '/api/public/consume/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSharesRoute = ApiPublicAdminSharesRouteImport.update({
  id: '/api/public/admin/shares',
  path: '/api/public/admin/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminLoginRoute = ApiPublicAdminLoginRouteImport.update({
  id: '/api/public/admin/login',
  path: '/api/public/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminConfigRoute = ApiPublicAdminConfigRouteImport.update({
  id: '/api/public/admin/config',
  path: '/api/public/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSharesCodeHeartbeatRoute =
  ApiPublicSharesCodeHeartbeatRouteImport.update({
    id: '/heartbeat',
    path: '/heartbeat',
    getParentRoute: () => ApiPublicSharesCodeRoute,
  } as any)
const ApiPublicSharesCodeDeactivateRoute =
  ApiPublicSharesCodeDeactivateRouteImport.update({
    id: '/deactivate',
    path: '/deactivate',
    getParentRoute: () => ApiPublicSharesCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/api/public/admin/config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/shares': typeof ApiPublicAdminSharesRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/receive/$code': typeof ReceiveCodeRoute
  '/api/public/admin/config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/shares': typeof ApiPublicAdminSharesRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/receive_/$code': typeof ReceiveCodeRoute
  '/api/public/admin/config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin/login': typeof ApiPublicAdminLoginRoute
  '/api/public/admin/shares': typeof ApiPublicAdminSharesRoute
  '/api/public/consume/$code': typeof ApiPublicConsumeCodeRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/download/$code': typeof ApiPublicDownloadCodeRoute
  '/api/public/shares/$code': typeof ApiPublicSharesCodeRouteWithChildren
  '/api/public/shares/create': typeof ApiPublicSharesCreateRoute
  '/api/public/shares/$code/deactivate': typeof ApiPublicSharesCodeDeactivateRoute
  '/api/public/shares/$code/heartbeat': typeof ApiPublicSharesCodeHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/receive'
    | '/send'
    | '/receive/$code'
    | '/api/public/admin/config'
    | '/api/public/admin/login'
    | '/api/public/admin/shares'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/receive'
    | '/send'
    | '/receive/$code'
    | '/api/public/admin/config'
    | '/api/public/admin/login'
    | '/api/public/admin/shares'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/receive'
    | '/send'
    | '/receive_/$code'
    | '/api/public/admin/config'
    | '/api/public/admin/login'
    | '/api/public/admin/shares'
    | '/api/public/consume/$code'
    | '/api/public/cron/cleanup'
    | '/api/public/download/$code'
    | '/api/public/shares/$code'
    | '/api/public/shares/create'
    | '/api/public/shares/$code/deactivate'
    | '/api/public/shares/$code/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  ReceiveCodeRoute: typeof ReceiveCodeRoute
  ApiPublicAdminConfigRoute: typeof ApiPublicAdminConfigRoute
  ApiPublicAdminLoginRoute: typeof ApiPublicAdminLoginRoute
  ApiPublicAdminSharesRoute: typeof ApiPublicAdminSharesRoute
  ApiPublicConsumeCodeRoute: typeof ApiPublicConsumeCodeRoute
  ApiPublicCronCleanupRoute: typeof ApiPublicCronCleanupRoute
  ApiPublicDownloadCodeRoute: typeof ApiPublicDownloadCodeRoute
  ApiPublicSharesCodeRoute: typeof ApiPublicSharesCodeRouteWithChildren
  ApiPublicSharesCreateRoute: typeof ApiPublicSharesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive_/$code': {
      id: '/receive_/$code'
      path: '/receive/$code'
      fullPath: '/receive/$code'
      preLoaderRoute: typeof ReceiveCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/create': {
      id: '/api/public/shares/create'
      path: '/api/public/shares/create'
      fullPath: '/api/public/shares/create'
      preLoaderRoute: typeof ApiPublicSharesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$code': {
      id: '/api/public/shares/$code'
      path: '/api/public/shares/$code'
      fullPath: '/api/public/shares/$code'
      preLoaderRoute: typeof ApiPublicSharesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$code': {
      id: '/api/public/download/$code'
      path: '/api/public/download/$code'
      fullPath: '/api/public/download/$code'
      preLoaderRoute: typeof ApiPublicDownloadCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cleanup': {
      id: '/api/public/cron/cleanup'
      path: '/api/public/cron/cleanup'
      fullPath: '/api/public/cron/cleanup'
      preLoaderRoute: typeof ApiPublicCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consume/$code': {
      id: '/api/public/consume/$code'
      path: '/api/public/consume/$code'
      fullPath: '/api/public/consume/$code'
      preLoaderRoute: typeof ApiPublicConsumeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/shares': {
      id: '/api/public/admin/shares'
      path: '/api/public/admin/shares'
      fullPath: '/api/public/admin/shares'
      preLoaderRoute: typeof ApiPublicAdminSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/login': {
      id: '/api/public/admin/login'
      path: '/api/public/admin/login'
      fullPath: '/api/public/admin/login'
      preLoaderRoute: typeof ApiPublicAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/config': {
      id: '/api/public/admin/config'
      path: '/api/public/admin/config'
      fullPath: '/api/public/admin/config'
      preLoaderRoute: typeof ApiPublicAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shares/$code/heartbeat': {
      id: '/api/public/shares/$code/heartbeat'
      path: '/heartbeat'
      fullPath: '/api/public/shares/$code/heartbeat'
      preLoaderRoute: typeof ApiPublicSharesCodeHeartbeatRouteImport
      parentRoute: typeof ApiPublicSharesCodeRoute
    }
    '/api/public/shares/$code/deactivate': {
      id: '/api/public/shares/$code/deactivate'
      path: '/deactivate'
      fullPath: '/api/public/shares/$code/deactivate'
      preLoaderRoute: typeof ApiPublicSharesCodeDeactivateRouteImport
      parentRoute: typeof ApiPublicSharesCodeRoute
    }
  }
}

interface ApiPublicSharesCodeRouteChildren {
  ApiPublicSharesCodeDeactivateRoute: typeof ApiPublicSharesCodeDeactivateRoute
  ApiPublicSharesCodeHeartbeatRoute: typeof ApiPublicSharesCodeHeartbeatRoute
}

const ApiPublicSharesCodeRouteChildren: ApiPublicSharesCodeRouteChildren = {
  ApiPublicSharesCodeDeactivateRoute: ApiPublicSharesCodeDeactivateRoute,
  ApiPublicSharesCodeHeartbeatRoute: ApiPublicSharesCodeHeartbeatRoute,
}

const ApiPublicSharesCodeRouteWithChildren =
  ApiPublicSharesCodeRoute._addFileChildren(ApiPublicSharesCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  ReceiveCodeRoute: ReceiveCodeRoute,
  ApiPublicAdminConfigRoute: ApiPublicAdminConfigRoute,
  ApiPublicAdminLoginRoute: ApiPublicAdminLoginRoute,
  ApiPublicAdminSharesRoute: ApiPublicAdminSharesRoute,
  ApiPublicConsumeCodeRoute: ApiPublicConsumeCodeRoute,
  ApiPublicCronCleanupRoute: ApiPublicCronCleanupRoute,
  ApiPublicDownloadCodeRoute: ApiPublicDownloadCodeRoute,
  ApiPublicSharesCodeRoute: ApiPublicSharesCodeRouteWithChildren,
  ApiPublicSharesCreateRoute: ApiPublicSharesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
